CXX=g++
CXXFLAGS=-Wall
#CXXFLAGS=-std=c++11 -Wall -Wextra -Wpedantic -Werror -Wfatal-errors -Winit-self -Wshadow -Wlogical-op -Wcomment -Wctor-dtor-privacy -D_GLIBCXX_DEBUG -fno-diagnostics-show-option

link: main.cc ll.cc
	$(CXX) $(CXXFLAGS) main.cc ll.cc -o link


