programs = Initiator.c Pell.c Composite.c Total.c
CFLAGS = -std=c11 -Wall

build: 
	gcc -o Initiator Initiator.c
	gcc -o Pell Pell.c
	gcc -o Composite Composite.c
	gcc -o Total Total.c

clean: 
	-rm Initiator 
	-rm Composite
	-rm Pell
	-rm Total
